data:
  raw_path: "data/raw/Flight_Booking.csv"


models:

  random_forest:
    type: "RandomForestRegressor"
    params:
      n_estimators: 100
      max_depth: 10

  linear_regressor:
    type: "LinearRegression"
    params: {}

  decision_tree:
    type: "DecisionTreeRegressor"
    params:
      max_depth: 10

